import { ProjectTemplate } from '../types';

export interface InfrastructureSelection {
  frontend: string;
  backend: string;
  database: string;
  storage: string;
  cache: string;
  queue: string;
}

export function generateOpenTofuHcl(
  projectName: string,
  template: ProjectTemplate,
  infra: InfrastructureSelection,
  environment: string = 'production'
): string {
  const sanitizedName = projectName.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  
  let hcl = `# ==============================================================================
# OpenTofu Infrastructure Blueprint - ${projectName}
# Generated by Nimbus Cloud Deployment Platform
# Environment: ${environment}
# Template: ${template.title}
# ==============================================================================

terraform {
  required_version = ">= 1.6.0"
  required_providers {
`;

  // Determine required providers based on infra
  const usesCloudflare = [infra.frontend, infra.backend, infra.database, infra.storage, infra.cache, infra.queue].some(
    val => val.toLowerCase().includes('cloudflare') || val.toLowerCase().includes('pages') || val.toLowerCase().includes('worker') || val.toLowerCase().includes('d1') || val.toLowerCase().includes('r2') || val.toLowerCase().includes('kv')
  );

  const usesAws = [infra.frontend, infra.backend, infra.database, infra.storage, infra.queue].some(
    val => val.toLowerCase().includes('aws') || val.toLowerCase().includes('ecs') || val.toLowerCase().includes('rds') || val.toLowerCase().includes('s3')
  );

  if (usesCloudflare) {
    hcl += `    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.25.0"
    }\n`;
  }

  if (usesAws) {
    hcl += `    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.38.0"
    }\n`;
  }

  hcl += `  }
}

# ------------------------------------------------------------------------------
# Provider Configurations
# ------------------------------------------------------------------------------
`;

  if (usesCloudflare) {
    hcl += `provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

variable "cloudflare_account_id" {
  type        = string;
  description = "Cloudflare Account ID"
}

variable "cloudflare_api_token" {
  type        = string;
  sensitive   = true;
  description = "Cloudflare API Token with Workers/Pages permissions"
}
\n`;
  }

  if (usesAws) {
    hcl += `provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}
\n`;
  }

  hcl += `# ------------------------------------------------------------------------------
# Provisioned Infrastructure Resources
# ------------------------------------------------------------------------------\n\n`;

  // 1. Frontend: Cloudflare Pages
  if (infra.frontend === 'Cloudflare Pages' || infra.frontend.includes('Pages')) {
    hcl += `# Cloudflare Pages Project
resource "cloudflare_pages_project" "app_frontend" {
  account_id        = var.cloudflare_account_id
  name              = "${sanitizedName}-frontend"
  production_branch = "main"

  build_config {
    build_command   = "npm run build"
    destination_dir = ".next"
    root_dir        = ""
  }

  deployment_configs {
    production {
      environment_variables = {
        NODE_VERSION = "20.11.0"
        FRAMEWORK    = "nextjs"
      }
    }
  }
}

output "pages_url" {
  value       = cloudflare_pages_project.app_frontend.subdomain
  description = "Deployment URL for Cloudflare Pages"
}\n\n`;
  }

  // 2. Backend: Cloudflare Workers
  if (infra.backend.includes('Workers') || infra.backend.includes('Edge')) {
    hcl += `# Cloudflare Worker API Engine
resource "cloudflare_worker_script" "api_backend" {
  account_id = var.cloudflare_account_id
  name       = "${sanitizedName}-worker-api"
  content    = file("dist/index.js")
  module     = true
  compatibility_date = "2024-04-01"

  kv_namespace_binding {
    name         = "KV_CACHE"
    namespace_id = cloudflare_workers_kv_namespace.app_cache[0].id
  }

  d1_database_binding {
    name        = "DB"
    database_id = cloudflare_d1_database.app_db[0].id
  }
}
\n`;
  } else if (infra.backend.includes('AWS ECS')) {
    hcl += `# AWS ECS Task Definition & Fargate Service
resource "aws_ecs_cluster" "app_cluster" {
  name = "${sanitizedName}-cluster"
}

resource "aws_ecs_task_definition" "app_task" {
  family                   = "${sanitizedName}-task"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  execution_role_arn       = var.aws_ecs_execution_role_arn

  container_definitions = jsonencode([
    {
      name      = "${sanitizedName}-api"
      image     = "123456789012.dkr.ecr.us-east-1.amazonaws.com/${sanitizedName}:latest"
      essential = true
      portMappings = [
        {
          containerPort = 3000
          hostPort      = 3000
        }
      ]
    }
  ])
}
\n`;
  }

  // 3. Database: Cloudflare D1
  if (infra.database.includes('D1')) {
    hcl += `# Cloudflare D1 Relational Edge Database
resource "cloudflare_d1_database" "app_db" {
  count      = 1
  account_id = var.cloudflare_account_id
  name       = "${sanitizedName}_d1_db"
}

output "d1_database_id" {
  value = cloudflare_d1_database.app_db[0].id
}\n\n`;
  } else if (infra.database.includes('PostgreSQL') || infra.database.includes('RDS')) {
    hcl += `# AWS RDS PostgreSQL Instance
resource "aws_db_instance" "app_postgres" {
  allocated_storage    = 20
  engine               = "postgres"
  engine_version       = "15.4"
  instance_class       = "db.t4g.micro"
  db_name              = "${sanitizedName.replace(/-/g, '_')}_db"
  username             = "admin_user"
  password             = var.db_password
  skip_final_snapshot  = true
}
\n`;
  }

  // 4. Storage: Cloudflare R2
  if (infra.storage.includes('R2')) {
    hcl += `# Cloudflare R2 Object Storage Bucket
resource "cloudflare_r2_bucket" "app_storage" {
  account_id = var.cloudflare_account_id
  name       = "${sanitizedName}-assets-bucket"
}

output "r2_bucket_name" {
  value = cloudflare_r2_bucket.app_storage.name
}\n\n`;
  } else if (infra.storage.includes('S3')) {
    hcl += `# AWS S3 Storage Bucket
resource "aws_s3_bucket" "app_s3" {
  bucket = "${sanitizedName}-media-storage"
}
\n`;
  }

  // 5. Cache: Cloudflare KV
  if (infra.cache.includes('KV')) {
    hcl += `# Cloudflare KV Key-Value Namespace
resource "cloudflare_workers_kv_namespace" "app_cache" {
  count      = 1
  account_id = var.cloudflare_account_id
  title      = "${sanitizedName}_kv_cache"
}\n\n`;
  }

  return hcl;
}
